
---
version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=LK
      - TRANSMISSION_WEB_HOME= #optional
      - USER= user
      - PASS= 1234
      - WHITELIST= #optional
      - PEERPORT= #optional
      - HOST_WHITELIST= #optional
    volumes:
      - /config/Transmission:/config
      - /Downloads/Transmission:/downloads
      - /Downloads/Transmission:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
